server:
  port: 9003

spring:
  application:
    name: balance-check-service

  datasource:
    url: jdbc:mysql://localhost:3306/balance_check_service_dev
    username: root
    password: Rishikumar12345
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
